### ISSUE TITLE
Customize the data structure

### ISSUE THREAD

**Issue by Robert-Frampton** [Robert-Frampton/metal-charts#1]
Currently billboard.js consumes data like this. Where the first element of each column array is the id of the column. That id can then be used in other config properties such as `types` and `colors`.

```javascript
data: {
	columns: [
		["data1", 30, 200, 100, 170, 150, 250],
		["data2", 130, 100, 140, 35, 110, 50]
	],
	types: {
		data1: "line",
		data2: "area-spline"
	},
	colors: {
		data1: "red",
		data2: "green"
	}
}
```

I find this confusing, especially considering that most developers will have to construct these arrays every time they need to pass data to the component. It also seems prone to bugs and side affects.

My suggestion to provide a more natural data structure, and then to map it to whatever billboard needs.

```javascript
columns: [
	{
		id: 'data1',
		data: [30, 200, 100, 170, 150, 250],
		type: 'line',
		color: 'red'
	},
	{
		color: 'green',
		data: [130, 100, 140, 35, 110, 50],
		id: 'data2',
		type: 'area-spline'
	}
]
```

That way we can simplify the api and make this more accessible to devs.

**Comment by blzaugg** [comment]
Can we consume both? I'm thinking in cases where someone already has some billboard.js formated data.

We could check if the first node is "data" than don't normalize the format.
